- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
- app/src/main/java/com/teamwss/websoso/ui/keyword/KeywordActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/main/home/HomeFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/recode/RecodeFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
- app/src/main/res/layout/activity_keyword.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_memo_write.xml
- app/src/main/res/layout/activity_novel_detail.xml
- app/src/main/res/layout/activity_post_novel.xml
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/fragment_home.xml
- closed #6 
- 이슈에 관한 작업을 완료하였습니다.
오타 지송 ㅋㅋ
> build : 폴더 구조, 폴더 이름, 폴더 이름 오타수정

- app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
- app/src/main/res/color/selc_bottom_nav_item.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/menu_bottom_nav.xml
- closed #2 
- 바텀네비게이션 color system을 적용하였습니다.
- recode 오타 또 찾아서 수정했습니다.
https://github.com/Team-WSS/WSS-Android/assets/52442547/361c5e74-67d6-4d45-bcb4-3cc3cd1a7612
> feat: 바텀네비게이션 design system 적용, 변경된 디자인 적용

- app/src/main/java/com/teamwss/websoso/data/NetworkModule.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/AuthService.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/AvatarService.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/MemoService.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/NovelService.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
- app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
- closed #30 
- 오류 이미지가 제대로 로딩되지 않는 오류를 수정하였습니다.
원리 자체는 별거 아닌데 상당히 많은 시간을 소비했군요 🥲
> fix: 이미지 로드 오류 수정

- app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
- app/src/main/res/layout/activity_post_novel.xml
- closed #32
- 패키지 누락 코드 추가하였습니다.
실수로 지웠었나봐요 죄송합니다 (꾸벅)
> fix: 바인딩 어댑터 빌드 오류 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageAdapter.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/changeName/ChangeNameActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/checkUserInfo/CheckUserInfoActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/model/Avatar.kt
- app/src/main/res/drawable/bg_gray100_radius_999dp.xml
- app/src/main/res/drawable/bg_primary100_radius_12dp.xml
- app/src/main/res/drawable/bg_white_radius_12dp.xml
- app/src/main/res/drawable/ic_book.xml
- app/src/main/res/drawable/ic_memo.xml
- app/src/main/res/drawable/ic_navigate_left.xml
- app/src/main/res/drawable/ic_navigate_right.xml
- app/src/main/res/layout/activity_change_name.xml
- app/src/main/res/layout/activity_check_user_info.xml
- app/src/main/res/layout/dialog_avatar.xml
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/layout/item_avatar.xml
- app/src/main/res/layout/item_search_novel.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- closed #14 
- 마이페이지 xml
- 닉네임변경 xml
- 계정정보 xml
- 아바타 바텀시트
- 닉네임 변경 조건 기능 구현
- 마이페이지 리사이클러뷰 
https://github.com/Team-WSS/WSS-Android/assets/144861180/ddc85afa-bbe5-4c2c-8ccd-f2eeb0941dcc
- 닉네임 변경 부분 코리 기다리면서 슬금슬금 뷰모델 만들어보겠습니다. 
- 대표캐릭터와 바텀시트에 있는 캐릭터들은 모션이 들어가는 캐릭어라 제가 들고있을 예정입니다. 
- 이슈에서 말씀드렸다시피 캐릭터 선택 부분은 확정뷰가 아니라서 일단은 가로 리사이클러뷰로 만들었습니다. 
- 캐릭터 선택 부분에 이미지가 작은 건 url 이미지라 인터넷 이슈로 작게 보이는 것 뿐입니다. 시간이 지나면 제대로 로드됩니다!!
> feat: my page view 구현

- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewHolder.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/MyPageViewModel.kt
- closed #
- 마이페이지 에러 수정
충돌 해결하면서 그전 커밋만하고 푸쉬하지 않은 것들이 적용이 안되었네요. 수정했습니다!
> fix: 마이페이지 에러 수정

- app/src/main/java/com/teamwss/websoso/data/remote/response/SearchNovelsResponse.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/NovelService.kt
- app/src/main/java/com/teamwss/websoso/data/remote/service/UserNovelService.kt
- app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/search/SearchAdapter.kt
- app/src/main/java/com/teamwss/websoso/ui/search/SearchViewHolder.kt
- app/src/main/java/com/teamwss/websoso/ui/search/searchViewModel/SearchViewModel.kt
- app/src/main/java/com/teamwss/websoso/util/BindingAdpater.kt
- app/src/main/res/layout/activity_search.xml
- app/src/main/res/layout/item_search_novel.xml
- closed #39
- 검색 기능 추가
- api 연결
- 무한스크롤 추가
- 반응형 검색 추가
- 선택된 item에 따라 post view로 이동
- post view에서 id를 받고 수정 가능
https://github.com/Team-WSS/WSS-Android/assets/127238018/493d23ff-0a04-4ebe-890f-36770aa40133
여러분 고지가 머지 않았습니당 파이팅이예요!!
> feat: search view api 연결

- app/src/main/java/com/teamwss/websoso/ui/main/record/RecordAdapter.kt
- app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/record/RecordViewModel.kt
- closed #48
- 메모 클릭리스너
- 메모아이디 토스트 메세지 반영하기
[Screen_recording_20240117_033436.webm](https://github.com/Team-WSS/WSS-Android/assets/144861180/1f9c6cc2-bfdd-4e8e-9fc4-7f9bcc825812)
> feat: record 메모 클릭리스너 구현

- app/src/main/java/com/teamwss/websoso/ui/main/library/LibraryFragment.kt
- app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerAdapter.kt
- app/src/main/java/com/teamwss/websoso/ui/main/library/adapter/LibraryViewPagerViewHolder.kt
- app/src/main/java/com/teamwss/websoso/ui/main/myPage/AvatarDialogFragment.kt
- closed #54 
- 바텀시트 dismiss 설정
- 서재뷰에서 서치뷰로 넘어가기 직전까지 설정
QA 화이팅!
> feat: QA전 디테일 추가

- app/src/main/java/com/teamwss/websoso/ui/main/record/RecordFragment.kt
- app/src/main/res/layout/fragment_record.xml
- app/src/main/res/values/strings.xml
- closed #57
- 기록 화면에 기록이 없을 경우 버튼 모양이 이상함, 멘트도 수정 필요
- 기록이 없는 경우 버튼 눌렀을 때 검색 화면으로 이동하는 기능 필요
https://github.com/Team-WSS/WSS-Android/assets/144861180/8ebbe641-ccef-4ab4-931b-633bd88c1942
> refactor: record ui 수정

- app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/dialog/PostSuccessDialog.kt
- app/src/main/java/com/teamwss/websoso/ui/search/SearchActivity.kt
- app/src/main/res/layout/activity_post_novel.xml
- closed #68
- 스택 관리와 intent 위치를 분석하여 새로 로직을 반영하였습니다
https://github.com/Team-WSS/WSS-Android/assets/127238018/30d9d6b5-6c63-4804-977b-1c5f7f0a2647
> refactor: post view 브로드캐스트 로직 대체

- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- closed #74
- post view에서 토글이 꺼진 상태로 등록시 null값이 반환되지 않는 오류 수정
> fix: post view 분기처리 수정

- app/src/main/java/com/teamwss/websoso/ui/main/MainActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- app/src/main/res/values/strings.xml
- closed #79
- post view와 연결된 스택을 정리합니다
https://github.com/Team-WSS/WSS-Android/assets/127238018/75c19e0e-caea-461d-923b-38f6e5b589df
샤라웃투 세훈
> refactor: post view와 연결된 스택 정리

- app/src/main/java/com/teamwss/websoso/util/CustomSnackBar.kt
- app/src/main/res/values/typography.xml
- closed #88
- 폰트 스타일 변경 (sp -> dp)
- 사용하지 않는 import 삭제
> refactor: style 수정

- app/src/main/res/layout/activity_novel_detail.xml
- app/src/main/res/layout/fragment_library.xml
- closed #91 
- 해결 완료
https://github.com/Team-WSS/WSS-Android/assets/52442547/cc29929d-5c6a-4d1c-876c-61549b25a6d3
왜 이게 풀렸을까요
> fix: 탭 아이템 선택 textColor 추가

- app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/postNovel/PostNovelActivity.kt
- app/src/main/res/layout/activity_novel_detail.xml
- app/src/main/res/layout/fragment_novel_info.xml
- closed #95 
- 레이팅 색상 수정
- 메모 뷰에서 작품 수정 뷰로 이동하는 로직 수정
- 함수 네이밍 수정
> refactor: 메모 뷰 2차 실시간 QA 대응

- app/src/main/res/layout/fragment_library.xml
- closed #94 
- 자짤한 색상을 변경하였습니다.
없음
웹소소 사랑해
> refactor: 2차 qa 변경사항 반영

- app/src/main/java/com/teamwss/websoso/ui/memoPlain/MemoPlainActivity.kt
- app/src/main/java/com/teamwss/websoso/ui/novelDetail/NovelDetailActivity.kt
- app/src/main/res/layout/fragment_novel_info.xml
- closed #100 
- 디자인 QA 반영
- 사용하지 않는 메서드 제거
- 메모 삭제 다이얼로그 뜬 후 스낵바 메시지 출력되는 로직 수정
없음
어푸어푸해주세요 아니면 강제 머지 할 거임 😏
> refactor: 메모 뷰 3차 QA 반영

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
- app/src/main/res/layout/activity_memo_plain.xml
- app/src/main/res/layout/activity_memo_write.xml
- closed #98 
- edittext에 adjustpan 속성이 적용되지 않는 이슈를 해결했습니다 ^-^
해결 완료!!
> refactor: 메모 작성 시 키보드 뒤에 숨어지는 이슈 해결

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/teamwss/websoso/ui/memoWrite/MemoWriteActivity.kt
- app/src/main/res/layout/activity_memo_write.xml
- app/src/main/res/values-v31/themes.xml
- app/src/main/res/values/themes.xml
- closed #109 
- 메모 작성 뷰 상태바 불투명 현상을 흰생 상태 바 테마 설정하며 수정했습니다.
> refactor: 메모 작성 뷰 상태바 흰색으로 수정
